workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini
    environment:
      java: 17
    scripts:
      - name: Build Android APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/**/*.apk
